scam_eater/samples/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.SampleCollectionFormView.as_view(), name="sample-collection-form"),
    path("sample/<slug:slug>/", views.SampleDetailView.as_view(), name="sample-detail"),
]

scam_eater/scam_eater/urls.py
from django.contrib import admin
from django.urls import path, include
from django.http import HttpResponse

urlpatterns = [
    path("", include("samples.urls")),
    path("admin/", admin.site.urls),
    path("robots.txt", lambda x: HttpResponse("User-Agent: *\nAllow: /", content_type="text/plain"), name="robots_txt"),
]

scam_eater/samples/models.py
import hashlib

from django.db import models
from django.urls import reverse


class Sample(models.Model):
    class Meta:
        indexes = [
            models.Index(fields=("sample_hash",)),
            models.Index(fields=("date_created",)),
            models.Index(fields=("date_modified",)),
        ]

    URL_REGEX = r"\b(?:https?:\/\/)?[-a-zA-Z0-9_\.]{1,256}\.[a-zA-Z]{2,7}\b[-a-zA-Z0-9()!@:%_\+.~#?&\/=]*\b"

    PLATFORM_EMAIL = "email"
    PLATFORM_PHONE = "phone"
    PLATFORM_TELEGRAM = "telegram"
    PLATFORM_DISCORD = "discord"
    PLATFORM_FACEBOOK = "facebook"
    PLATFORM_MESSENGER = "messenger"
    PLATFORM_WHATSAPP = "whatsapp"
    PLATFORM_TWITTER = "twitter"
    PLATFORM_REDDIT = "reddit"
    PLATFORMS = (
        (PLATFORM_EMAIL, "Email"),
        (PLATFORM_PHONE, "Phone/Mobile"),
        (PLATFORM_TELEGRAM, "Telegram"),
        (PLATFORM_DISCORD, "Discord"),
        (PLATFORM_FACEBOOK, "Facebook/Meta"),
        (PLATFORM_MESSENGER, "Messenger"),
        (PLATFORM_WHATSAPP, "Whatsapp"),
        (PLATFORM_TWITTER, "Twitter/X"),
        (PLATFORM_REDDIT, "Reddit"),
    )

    STATUS_NEW = "new"
    STATUS_REPORTED = "reported"
    STATUS_INVALID = "invalid"
    STATUS_SUCCESS = "success"
    STATUS_CANNOT_PROCEED = "no_activity_success"
    STATUS_DUPLICATED = "duplicate"
    STATUS_NOT_ENOUGH_INFO = "not_enough_info"
    STATUS_STATES = (
        (STATUS_NEW, "New"),
        (STATUS_INVALID, "Invalid"),
        (STATUS_REPORTED, "Report(s) made"),
        (STATUS_SUCCESS, "Successfully taken-down"),
        (STATUS_CANNOT_PROCEED, "Can't take action"),
        (STATUS_DUPLICATED, "Duplicate"),
        (STATUS_NOT_ENOUGH_INFO, "Not enough information"),
    )
    STATUS_EXPLANATIONS = {
        STATUS_NEW: "We've received your scam sample and are yet to start processing it. Come back later to see the results ⌚",
        STATUS_REPORTED: "We've started reporting your scam to the relevant places. Hopefully it will be taken down soon! 🧑‍💻",
        STATUS_INVALID: "Sorry, but it looks like the data you gave us was invalid. We can't work with this 😕",
        STATUS_SUCCESS: "Hooray! 🎉 The scam has been taken down, thanks for reporting it to us! 😁",
        STATUS_CANNOT_PROCEED: "We tried, but it looks like we can't do much here. 😕",
        STATUS_DUPLICATED: "Looks like this sample is a duplicate of another one we found. But don't worry, your submission will be used to count how widespread this scam is! 📊",
        STATUS_NOT_ENOUGH_INFO: "We are not sure if this is a scam. There isn't enough information to take any action on this one, sorry 🙁",
    }

    STATUS_REASON_CONN_FAILED = "connection_failed"
    STATUS_REASON_NO_LINKS = "no_links_provided"
    STATUS_REASON_NO_REPORTING = "no_reporting_mechanism"
    STATUS_REASON_DORMANT = "alive_no_longer_active"
    STATUS_REASONS = (
        (STATUS_REASON_CONN_FAILED, "Cannot connect to website"),
        (STATUS_REASON_NO_LINKS, "No websites provided in sample"),
        (STATUS_REASON_NO_REPORTING, "No way to report abuse"),
        (STATUS_REASON_DORMANT, "Able to connect but scam is no longer there"),
    )

    raw_sample = models.TextField(blank=False, null=False)
    sample_hash = models.CharField(max_length=256, blank=False, null=False)
    sample_scammer_origin = models.CharField(
        max_length=512,
        blank=True,
        null=True,
        default=None,
        help_text="The email, phone or other ID of the scammer",
    )
    sample_platform_origin = models.CharField(
        max_length=64,
        blank=True,
        null=True,
        choices=PLATFORMS,
        help_text="The communication medium where this scam was found",
    )
    status = models.CharField(
        max_length=64,
        blank=False,
        null=False,
        choices=STATUS_STATES,
        default=STATUS_NEW,
    )
    status_reason = models.CharField(
        max_length=64, blank=True, null=True, choices=STATUS_REASONS, default=None
    )
    scam_score = models.FloatField(
        blank=False,
        null=True,
        default=None,
        help_text="How likely this is to be a scam. 0=not a scam, 1=scam.",
    )

    reporter_ip = models.CharField(
        max_length=46,
        blank=True,
        null=True,
        help_text="The IP address of the user who reported this",
    )
    reporter_country_code = models.CharField(max_length=2, blank=True, null=True)

    date_created = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)

    def save(self, *args, **kwargs):
        self.sample_hash = hashlib.sha1(self.raw_sample.encode()).hexdigest()
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("sample-detail", kwargs={"slug": self.pk})

    @property
    def summary_text(self) -> str:
        return self.STATUS_EXPLANATIONS.get(
            self.status,
            "There's supposed to be a description here but it looks like we don't have one. Oops! 😅",
        )

    @property
    def status_reason_text(self) -> str:
        for status_reason_entry in self.STATUS_REASONS:
            if status_reason_entry[0] == self.status_reason:
                return status_reason_entry[1]
        return ""

    @property
    def status_text(self) -> str:
        for status_entry in self.STATUS_STATES:
            if status_entry[0] == self.status:
                if self.status_reason:
                    return f"{status_entry[1]} - {self.status_reason_text}"
                else:
                    return status_entry[1]
        return "N/A"

    @property
    def sample_emoji(self) -> str:
        if self.scam_score is None:
            return "❓"

        if 0 <= self.scam_score <= 0.25:
            return "🤔"
        elif 0.25 < self.scam_score <= 0.5:
            return "🤨"
        elif 0.5 < self.scam_score <= 0.75:
            return "⚠"
        elif 0.75 < self.scam_score <= 1:
            return "⛔"
        else:
            return "😶‍🌫️"

    @property
    def reporting_activities(self):
        return ReportingActivity.objects.filter(sample=self)


class DomainName(models.Model):
    class Meta:
        indexes = [models.Index(fields=("name",))]

    name = models.CharField(max_length=256, blank=False, null=False)
    reported_for_abuse = models.BooleanField(blank=False, null=False, default=False)

    date_created = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)


class Website(models.Model):
    class Meta:
        indexes = [models.Index(fields=("date_created",))]

    sample = models.ForeignKey(to=Sample, on_delete=models.CASCADE)
    domain_name = models.ForeignKey(
        to=DomainName, null=True, on_delete=models.SET_NULL, default=None
    )

    url = models.CharField(max_length=512, blank=False, null=False)

    date_created = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)


class ReportingActivity(models.Model):
    class Meta:
        indexes = [models.Index(fields=("date_created",))]

    sample = models.ForeignKey(to=Sample, on_delete=models.CASCADE)

    title = models.CharField(max_length=128, blank=False, null=False)
    description = models.CharField(max_length=128, blank=True, null=True)
    activity_date = models.DateTimeField(
        blank=True,
        null=True,
        default=None,
        help_text="The date in which the activity actually happened",
    )

    date_created = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)

    @property
    def time_occurred(self):
        if self.activity_date:
            return self.activity_date
        return self.date_created

scam_eater/samples/views.py
import re

from django import forms
from django.core.exceptions import ValidationError
from django.views.generic import DetailView
from django.views.generic.edit import CreateView
from samples.models import Sample


class SampleCollectionForm(forms.ModelForm):
    class Meta:
        model = Sample
        fields = ["raw_sample"]

    raw_sample = forms.CharField(
        required=True,
        strip=True,
        min_length=10,
        max_length=65535,
        label="",
        widget=forms.widgets.Textarea(),
    )

    def clean_raw_sample(self):
        raw_sample = self.cleaned_data["raw_sample"]

        # Check that a website is in the sample
        if not re.findall(Sample.URL_REGEX, raw_sample):
            raise ValidationError(
                "You must provide a scam sample that contains a website"
            )

        return raw_sample


class SampleCollectionFormView(CreateView):
    model = Sample
    form_class = SampleCollectionForm
    template_name = "scam_form.html"

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["initial"] = {"raw_sample": self.request.GET.get("_", "")}
        return kwargs


class SampleDetailView(DetailView):
    model = Sample
    slug_field = "id"
    template_name = "scam_sample.html"

scam_eater/samples/templates/base.html
{% load static tailwind_tags %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <title>{% block title %}Scam Eater - By Marcus Belcastro{% endblock %}</title>

        {% tailwind_css %}
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Rubik&display=swap" rel="stylesheet">
        {% block header %}{% endblock %}
    </head>

    <body class="bg-gray-900 font-rubik">
        <div id="content">
            {% block content %}{% endblock %}
        </div>

        <footer>
            <div class="container mx-auto text-center">
                <hr class="w-3/4 mx-auto border-t-2 border-gray-500 mb-4">
                <p class="h-10 text-gray-600">
                Created by <a class="underline" href="https://marcusbelcastro.com/" target="_blank">Marcus Belcastro</a> &copy; 2023
                </p>
            </div>
        </footer>
    </body>

</html>

scam_eater/samples/templates/scam_form.html
{% extends 'base.html' %}

{% block content %}
<div class="text-white h-screen flex flex-col justify-center items-center px-4">
    <div class="text-center font-bold">
        <h1 class="text-4xl md:text-6xl mb-4">Copy-paste the scam into the box below 👇</h1>
        <h2 class="text-2xl md:text-4xl mb-8">We will handle the rest 🧑‍💻</h2>
    </div>

    <form method="post" class="text-center w-full md:w-96">
        {% csrf_token %}

        <div class="mb-4">
            <textarea name="raw_sample" id="id_raw_sample" class="w-full h-44 bg-gray-700 text-gray-200 border rounded-lg p-4 mb-4 focus:outline-none focus:ring-2 focus:ring-purple-500"></textarea>
        </div>

        <div class="mb-4">
            {{ form.raw_sample.errors }}
        </div>

        <button type="submit" class="bg-purple-800 font-bold text-white py-2 px-4 rounded-lg hover:bg-purple-700">Submit</button>
    </form>
</div>
{% endblock %}

scam_eater/samples/templates/scam_sample.html
{% extends 'base.html' %}
{% load sample_template_utils %}

{% block header %}
    <style>
        {% comment %} Custom styling for the timeline lines {% endcomment %}
        div > .timeline-item {
            position: relative;
        }
        
        div > .timeline-item::before {
            content: "";
            position: absolute;
            top: 2rem;
            left: 0.92rem;
            border-left-width: 4px;
            border-left-style: dotted;
            border-left-color: #312e81;
            height: 8rem;
            opacity: 30%;
        }

        .timeline-item:last-child::before {
            display: none;
        }
    </style>
{% endblock %}

{% block content %}
<div class="text-white grid grid-cols-1 justify-center items-center px-8 mx-auto max-w-4xl">

    {% comment %} Summary text at the top {% endcomment %}
    <div class="text-center my-16">
        <p class="text-lg mb-8">⭐ Tip: Bookmark this page to keep track of this scam ⭐</p>
        <p class="text-2xl font-bold">👉 {{ object.summary_text }}</p>
    </div>

    {% comment %} Scam analysis {% endcomment %}
    <div class="text-center mb-16">
        <p class="text-9xl mb-4">{{ object.sample_emoji }}</p>

        <div class="w-full px-16">
            <div class="relative w-full mb-2">
                <div class="w-full h-10 bg-gray-500 rounded-full"></div>
                <div class="w-full h-10 bg-red-600 rounded-full absolute top-0 left-0" style="width:{{ object.scam_score|percentage }};"></div>
            </div>

            <div class="flex flex-row justify-center w-full">
                <p class="pl-4">|</p>
                <p class="flex-grow text-center">|</p>
                <p class="pr-4">|</p>
            </div>

            <div class="flex flex-row justify-center w-full">
                <p class="w-16 text-left">Not sure</p>
                <p class="flex-grow text-center">Looks suspicious</p>
                <p class="w-16 text-right">Scam</p>
            </div>
        </div>
    </div>

    {% comment %} Details of the sample {% endcomment %}
    <div class="text-center text-lg mb-16">
        <p class="mb-4"><span class="font-bold">💬 Status: </span>{{ object.status_text }}</p>
        <p><span class="font-bold">🕒 Created at: </span>{{ object.date_created|date }}</p>
    </div>

    {% comment %} Sample activity {% endcomment %}
    <div class="flex flex-col justify-center items-center mb-16">
        {% for activity in object.reporting_activities %}
            <div class="timeline-item flex flex-row w-full justify-center items-center mb-8">
                <div class="basis-2/12">
                    <div class="w-8 h-8 bg-purple-900 rounded-full cursor-pointer mr-auto" title="{{ activity.time_occurred }}"></div>
                </div>
                <div class="basis-10/12 shrink bg-gray-800 border-4 border-purple-900 rounded-md p-4 ml-4">
                    <h5 class="font-bold text-xl">{{ activity.title }}</h5>
                    <p class="text-md">{{ activity.description }}</p>
                </div>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}